FileService/FileService/Controllers/BlobController.cs
using System.IO;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FileService.Models;
using Microsoft.WindowsAzure.Storage; // Namespace for CloudStorageAccount
using Microsoft.WindowsAzure.Storage.Blob; // Namespace for Blob storage types
using System.Threading.Tasks;

namespace FileService.Controllers
{
    public class BlobController: Controller
    {
        public ActionResult CreateBlobContainer()
        {
            BlobManager bm = new BlobManager();
            CloudBlobContainer container = bm.GetContainer("mysamplecontainer");
            ViewBag.Success = container.CreateIfNotExistsAsync().Result;
            ViewBag.BlobContainerName = container.Name;
            return View();
        }

        public IActionResult HomePage()
        {
            return View();
        }

        //========================Upload File================================
        [HttpPost]
        public async Task<IActionResult> UploadFile(List<IFormFile> files)
        {
            var blobManager = new BlobManager();

            foreach (IFormFile file in files)
            {
                await blobManager.UploadFile("mysamplecontainer", file);
            }

            return View();
        }

        //=================download=============================
        //https://docs.microsoft.com/en-us/azure/visual-studio/vs-storage-aspnet-core-getting-started-blobs
        public ActionResult ListBlobs()
        {
            BlobManager bm = new BlobManager();
            CloudBlobContainer container = bm.GetContainer("mysamplecontainer");
            List<string> blobs = new List<string>();
            BlobResultSegment resultSegment = container.ListBlobsSegmentedAsync(null).Result;
            foreach (IListBlobItem item in resultSegment.Results)
            {
                if (item.GetType() == typeof(CloudBlockBlob))
                {
                    CloudBlockBlob blob = (CloudBlockBlob)item;
                    blobs.Add(blob.Name);
                }
                else if (item.GetType() == typeof(CloudPageBlob))
                {
                    CloudPageBlob blob = (CloudPageBlob)item;
                    blobs.Add(blob.Name);
                }
                else if (item.GetType() == typeof(CloudBlobDirectory))
                {
                    CloudBlobDirectory dir = (CloudBlobDirectory)item;
                    blobs.Add(dir.Uri.ToString());
                }
            }

            return View(blobs);
        }

        public ActionResult DownLoadFile(string id)
        {
            //MemoryStream ms = new MemoryStream();
            //BlobManager bm = new BlobManager();
            //CloudStorageAccount storageAccount = bm.InitializeAccount();
            //CloudBlobClient BlobClient = storageAccount.CreateCloudBlobClient();
            //CloudBlobContainer c1 = BlobClient.GetContainerReference("mysamplecontainer");
            ////bool hasContainer = await c1.CreateIfNotExistsAsync();
            //if (c1.CreateIfNotExistsAsync())
            //{
            //    CloudBlob file = c1.GetBlobReference(id);

            //    if (file.ExistsAsync())
            //    {
            //        file.DownloadToStreamAsync(ms);
            //        Stream blobStream = file.OpenReadAsync().Result;
            //        return File(blobStream, file.Properties.ContentType, file.Name);
            //    }
            //    else
            //    {
            //        return Content("File does not exist");
            //    }
            //}
            //else
            //{
            //    return Content("Dir does not exist");
            //}

            
            MemoryStream ms = new MemoryStream();
            BlobManager bm = new BlobManager();
            CloudStorageAccount storageAccount = bm.InitializeAccount();

            CloudBlobClient BlobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer c1 = BlobClient.GetContainerReference("mysamplecontainer");
            CloudBlob file = c1.GetBlobReference(id);
            file.DownloadToStreamAsync(ms);
            Stream blobStream = file.OpenReadAsync().Result;
            return File(blobStream, file.Properties.ContentType, file.Name);
            
        }

        [Route("DeleteFile/{fileName}")]
        [HttpGet]
        public async Task<bool> DeleteFile(string fileName)
        {
            MemoryStream ms = new MemoryStream();
            BlobManager bm = new BlobManager();
            CloudStorageAccount storageAccount = bm.InitializeAccount();
            CloudBlobClient BlobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = BlobClient.GetContainerReference("mysamplecontainer");
            try
            {
                if (await container.ExistsAsync())
                {
                    CloudBlob file = container.GetBlobReference(fileName);

                    if (await file.ExistsAsync())
                    {
                        await file.DeleteAsync();
                    }
                }
                return true;
            }
            catch
            {
                return false;
            }
        }


        public IActionResult DeleteBlob()
        {
            return View();
        }

        /*
        [Route("DeleteFile/{fileName}")]
        [HttpGet]
        public async Task<bool> DeleteFile(string fileName)
        {
            BlobManager bm = new BlobManager();
            CloudStorageAccount storageAccount = bm.InitializeAccount();
            CloudBlobClient BlobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer c1 = BlobClient.GetContainerReference("mysamplecontainer");
            var blob = c1.GetBlobReference(fileName);
            bool x =  await blob.DeleteIfExistsAsync();
            return x;
      
        }
        */
    }
}

FileService/FileService/Views/Blob/DeleteBlob.cshtml
<li><a asp-area="" asp-controller="Blob" asp-action="DeleteFile">Delete blob</a></li>

FileService/FileService/Views/Blob/DownloadFile.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
    </head>
    <body>
        <a href="/home/DownloadFile">Click to get file</a>
    </body>
</html>

FileService/FileService/Views/Blob/HomePage.cshtml
<div style="text-align:center; margin-top: 20px;">
    <h4>
        Upload, Download and Delete Blob Files using ASP.NET Core and Angular 8
    </h4>
</div>

<div class="blobstorage-section">
    <i class="fa fa-plus fa-2x" style="cursor: pointer; color: darkslateblue;" (click)="addFile()"></i>  Add new files to Blob
    <input style="display: none;" type="file" id="fileUpload" #selectedFile [(ngModel)]="fileUpload" (click)="selectedFile.value = null" value="" (change)="handleFileInput($event.target.files)" />
    <table style="margin-top: 20px;">
        <tr>
            <th class="column1">Uploaded Files</th>
            <th class="column2" style="text-align:center;">Download</th>
            <th class="column3" style="text-align:center;">Delete</th>
        </tr>
        <tr *ngFor="let file of files">
            <td class="column1">{{file}}</td>
            <td class="column2" style="text-align:center;cursor: pointer;" (click)="downloadFile(file)"><i class="fa fa-download"></i></td>
            <td class="column3" style="text-align:center;" (click)="deleteFile(file)">
                <img alt="Group Audit" src="../assets/icon-download.png" />
            </td>
        </tr>
    </table>
</div>
<form method="post" enctype="multipart/form-data" asp-controller="Blob" asp-action="UploadFile">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload one or more files using this form:</p>
            <input type="file" name="files" multiple>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload">
        </div>
    </div>
</form>

FileService/FileService/Views/Blob/ListBlobs.cshtml

<h2>List blobs</h2>

<ul>
    @foreach (var item in Model)
    {
        <li>  <a href="/Blob/DownloadFile?id=@item">@item</a></li>
    }
</ul>

<!--
@model List<string>
@{
    ViewBag.Title = "List blobs";
}

<h2>List blobs</h2>

<ul>
    @foreach (var item in Model)
    {
        <li>@item</li>
    }
</ul>
<li><a asp-area="" asp-controller="Blob" asp-action="ListBlobs">List blobs</a></li>
-->

FileService/FileService/Views/Blob/UploadFile.cshtml
<body>

    <h1> Success! </h1>
</body>